language: python
python:
- '3.5'
before_install:
- pip install -r requirements.txt
- git clone https://github.com/alexandrevicenzi/Flex.git

install:
- cp -r themes/templates Flex/templates
- pelican-themes -i Flex/
script:
- make html

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: seyiobaweya.tech
  skip_cleanup: true
  local_dir: output

after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

env:
  global:
  - secure: bXBdnYQon+lp7li8VJf6tTbwhZqQFpa2zbhrB009EiNSBB8v5gtzZj30bk8gU503MVeg3nEH1pxei18ObyLRxlrQ0x9D26xzWEWY/ewM4DEv1YzpU3w1x0kx1fYwpPf4bW4gQp389HxuJbHF3hAn7JjJSgCmyi//YsT9e2+mXsaN4uYWyGjbgLsa/IbiibK1I3nKg17Kp4A6IahscBPHF4g4rUzfVbQYvluVzl2wO4rhDpNYzS51Mkl0Wb3XBMd+pAJnvHSZUrr/sJsEwrnm5m0ORhtbAG7oJp4eBEJETaesIcYIW6rrilft1v6h1b0Wj9XXOpCoRuQkdpKcgpd3wXvjXPMZ9HzTsJ3rXeZkTTlgRCRb2RP6Fs2d4Y2KT0+OIrKtBkhrM6t6JthKlHrwyMc+M8GX/GY7CNQ7mkht8r3FtDk6Sj7rR406hbikR4C8/g0c6aHP03P2gP/lY+IGlLUWq6ZuMX+d+oG/SxK4IG1We033oS+r0oVp0+oiDWjcM2gnCG14263mxc5GtWPACSp7sqrcZgoqlUVzoNgICNMLFhLZsWxjDdfTrJUn7NmetOba5E/vAhWP6dc2raYcD613+5Zfv3t6nWAMRY2pJfxWIhiE2y7Ej32mA1vLr2cx03WdEpYJhqQdPaNnlFJ77Bmjs6Rw71DlnhdTVrzS3Zs=
  - secure: euHhmfg+o1QNnYvlgnci4ujeBOenx1R/jcB6shR4GTNArsA/HRs42PjisbcaLJZu7Sm+OEiUS4Q90/AOwzHxqzKy9fdSOnv3u7nBwWKvyS0mi2LJqdYYc6FtT2aeiTGexhhTYSX0hIF7ceSeFeeTWKtmhAWEvOdHB1SjZja3OYddtTKnoKUaqCIlMAZogP9Yl2G3spL4vTABC0lRZ5Q0X2NoNgl3RV6mGwuh3ZVmVRrCf7fcYYQgurSPV8fvlXOZM37AfKQdOazrgbTQmKG18Lg32IIbZdfAfYF0txbTLCZA4dL24gJ0u9BEwIqdERqhEIY6VGVl38n6uboVAGrmhIpVwyNN2bI/9s8N3G52cL2oBQCmIiv2XzUDcJvDEpQEyVv2Plj1XvSUQ6DL4siWE5W0ja2XPzPcl1BeUT3sHQAyUuSu2zWdVFXyJp6Vlgrxwz1/RmzMD5Q9toyqXp3F9r3c/EIXQ97k9/qiOy1fw6tm1M5zeyScEMfJFr6HYalWPVWR7Fe7Cf6TdrYYCyTbehg7vUdYKvSUKqZpoGX19qSG6sFaXZw/sI9kmYa/mS4og5yqTw7CnRz4mdwovOOrxxpiPdNXRHIhyiFoiFSI06C8bovzWLnht0WN41NLSZS8C89MhyvuSxLewpdxuFjk39pfCbDFVFX2QPtwRMk1wZY=
  - secure: Sw11yyvDiBtvZavOEVAjKMNgE8IXvcIQEQi/MU30PhZCpqiCEHQDpbClaFBK6dB29UqBdgeeJrf3YGPlsH+CnHvcaMq3Cd22j2pCBoASUPQ6FPLvB5kT6d4KPTtbQK/ZQZ+Lf56hg/32Drghvb1tk6N1Hky9i3UnjC0eJwhHKVhlUND5nNGsQ7uY92IxIavp5KA9EOsXz9IAQ5dJUEQ6AJ+UA4t51Y7w0cUXTtGuiYTdLXu0uYRNCzys+/S+ISdzLerCO5Har/LtI3r/c85wyvj5lhc9Nu9ucTdIircbgD1yzdQhb6XI+dAuh2wzZ0OGesK/yMmH0LXV0B8antBZ1KVgdXBfyT0SzJxKwRHQWdAYTNFlq+G7EFrZjfQ3Nm7rfaAUUQU6UycEicc/SmlhDrpnj0mUZer2VN16Udo/fTSUlX2WpLInRVXHduNlG8P8gAC6nenk7Hkx93mPeEcwcvLpR6mzc+xFhvFatfl6qWK2io/ro32kGSOkmrvf/RKWscPjUOUoPCDhZgXu8MrABOZTXApt8y4q647TULqHU7U3bgx8G/p1rmfR8TyTLGj3spWRq13HX+526GF4nC0kqCR/TuKH9mY8WfAhd/EUSUW6S4M3C0Z9eEC+6joDGM4/6TWAvIczToKVpCdClpe6D2b7QUoo6gVIgEsUBqiiO/0=
  - secure: Fdbz5XhUZWQXjsLRwcAEjqcLTXUTEWsUsnQTVJC/YC/6KoPvdhdNH2bWRttYPRHCLNDuEW5JhUHnO7I26VC/eA/uVGCgVBWK/0T+Pv41p0qIOTdBQV8VNLJi8iyYY8MPLQo9Ucw/xmtqb5rgKONAeeZX0yBL72ToMvVsV/Pd/5/f9doIbrC+C9g7A5i0O5/C8PwsV7dUf254Uu4EnVFajr/UVwYhjfWkpZOECwRNXgx06PVxLZeqg7DXSbFKrrc5XZcszE7/eT5P5o+lqmWjw2CPycQTs/t/DnjzoZcd046T4ChnEiDAhcwAKS/voltIoU2blWfaNddZeN5UFQG7Wj1b1vkp9EDo+3NpgDfUPCkKX2hbpMtWOWOIKY+bKsAN1tgvjmctV6FSzkktEWxh/Fbln32oGJO/4oAp79BNWELsNqYoRGh/TGujkKwyAmMJXktATsajnbOn1T8kSgCQKvo1ADroJvMX5zv381sgwfhXRvyhbbdb9Gw3NtYJ8TcJrCEUcYlm3ou2rbKocqwBh280DDJB/tWlDHMay+CVIGeQ3q4kD90JcViDZdPYs1b8Los5pexsNHfnCcfwxiBOUqM4qCtNgXrEk5+gOLCacOKuEFjAQEcbSUssieYs4es/DMCMdGaO2vhIxgJHvzaVGfr0scr0eAlPCLzi6Bfv5gg=
