language: python
python:
- '3.5'
before_install:
- pip install -r requirements.txt
- git clone https://github.com/alexandrevicenzi/Flex.git
install:
- cp -r themes/templates Flex/templates
- pelican-themes -i Flex/
script:
- make html
deploy:
  provider: s3
  access_key_id: AKIAQZPZYSPLRGXIGTOC
  secret_access_key:
    secure: AxvGLJ+TEfMf0lsPDblzGR6c4Hnpb3TV/Ec9hf4SSkKfolBk4erZ35WEKnePvqzQhY7eqkUxytePNlGeaqXnoLw6VuZqarcoOHne1IomP1298HGCiSz3QvYAXq4QtcJWEHTyKFIiivmwWaqyKOUCCcH/0T//S7c9HGdCHUg8ZFT1Zi7LsFfV1JCKKqWL1+AmP0Ds08ODmoYSMHHrTxbepeHpkU4zipVeq5OXRanqlbrk1em13NVtTI0AuuakedmE0J7A4KnotBKfojlnoV4Ams/hVEVub8FU728UhGaVleQATUAzO246pBu3Xup6VQ7Pt7zRdsp3M76fYQhO+hKKrD1zGb9ZAGoJuMapLo8Z+hvkLGABAgx8y2puQN2FaFOPmX67MpcadRjc/7UYQQHEgN0F60QSGeKBTerRKp/dOwKPEAAe2SFjSTDW5pOSf1qT8876Bif1wsyQtRIhOwrNmUnoifM0Evf1isnw4f8TMj0+PLiNEUXPzfn2YFttI1vb3Ga2aqiWw/IZmtZ/JD9DjoiGCReBbBGp4WpvF1izUIE0zb4miYTrvzrIRbzaBhqtC5xwrhMTUfEbTcBxqkF0iTGcfua4EQAkZeOpjAWB6hv77+9Mv8Qx7YR8+uqC8ECsEsKx2EDCqaqsaZoK4vJclx2cWYBSECWF5ycZ6bmtP6w=
  bucket: seyiobaweya.tech
  local-dir: output
  region: eu-west-2
  acl: public_read, bucket_owner_full_control
  on:
    repo: seyio91/sample-blog
  skip_cleanup: true

after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
env:
  global:
  - secure: Fdbz5XhUZWQXjsLRwcAEjqcLTXUTEWsUsnQTVJC/YC/6KoPvdhdNH2bWRttYPRHCLNDuEW5JhUHnO7I26VC/eA/uVGCgVBWK/0T+Pv41p0qIOTdBQV8VNLJi8iyYY8MPLQo9Ucw/xmtqb5rgKONAeeZX0yBL72ToMvVsV/Pd/5/f9doIbrC+C9g7A5i0O5/C8PwsV7dUf254Uu4EnVFajr/UVwYhjfWkpZOECwRNXgx06PVxLZeqg7DXSbFKrrc5XZcszE7/eT5P5o+lqmWjw2CPycQTs/t/DnjzoZcd046T4ChnEiDAhcwAKS/voltIoU2blWfaNddZeN5UFQG7Wj1b1vkp9EDo+3NpgDfUPCkKX2hbpMtWOWOIKY+bKsAN1tgvjmctV6FSzkktEWxh/Fbln32oGJO/4oAp79BNWELsNqYoRGh/TGujkKwyAmMJXktATsajnbOn1T8kSgCQKvo1ADroJvMX5zv381sgwfhXRvyhbbdb9Gw3NtYJ8TcJrCEUcYlm3ou2rbKocqwBh280DDJB/tWlDHMay+CVIGeQ3q4kD90JcViDZdPYs1b8Los5pexsNHfnCcfwxiBOUqM4qCtNgXrEk5+gOLCacOKuEFjAQEcbSUssieYs4es/DMCMdGaO2vhIxgJHvzaVGfr0scr0eAlPCLzi6Bfv5gg=
