language: python
python:
- '3.5'
before_install:
- pip install -r requirements.txt
install:
- pelican-themes -i themes/Flex/
script:
- pelican content -s publishconf.py


deploy:
  provider: s3
  access_key_id: AKIAQZPZYSPLRGXIGTOC
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: seyiobaweya.tech
  local-dir: output
  region: eu-west-2
  on:
    repo: seyio91/sample-blog
  skip_cleanup: true
  acl: public_read


after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
