---
language: python
python:
  - "3.5"
before_install:
  - pip install -r requirements.txt
  - git clone https://github.com/alexandrevicenzi/Flex.git
install:
  - cp -r themes/templates Flex/templates
  - pelican-themes -i Flex/
script:
  - make html